zookeeper:
  autopurge:
    purgeInterval: 1

query-service:
  configVars:
    ClickHouseUrl: http://signoz-clickhouse:9000?username=clickhouse_operator&password=clickhouse_operator_password
    STORAGE: clickhouse

cloud: aws

clickhouseOperator:
  enabled: true
  storage: 20Gi
  serviceType: ClusterIP
