apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flattener-processor.fullname" . }}
  labels:
    {{- include "flattener-processor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "flattener-processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flattener-processor.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "flattener-processor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - "/root/flattener"
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          env:
          - name: KAFKA_BROKER
            value: {{ .Values.configVars.KAFKA_BROKER }}
          - name: KAFKA_INPUT_TOPIC
            value: {{ .Values.configVars.KAFKA_INPUT_TOPIC }}
          - name: KAFKA_OUTPUT_TOPIC
            value: {{ .Values.configVars.KAFKA_OUTPUT_TOPIC }}
            
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
