apiVersion: batch/v1
kind: Job
metadata:
  name: set-retention
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
          - name: set-retention
            image: theithollow/hollowapp-blog:curl
            volumeMounts:
            - name: retention-config-volume
              mountPath: /app/retention-spec.json
              subPath: retention-spec.json
            args:
            - /bin/sh
            - -c
            - "curl -X POST -H 'Content-Type: application/json' -d @/app/retention-spec.json http://signoz-druid-router:8888/druid/coordinator/v1/rules/flattened_spans"

      volumes:
          - name: retention-config-volume
            configMap:
              name: retention-config

      restartPolicy: Never
  backoffLimit: 8