apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: hotrod
  name: hotrod
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hotrod
  strategy: {}
  template:
    metadata:
      labels:
        service: hotrod
    spec:
      containers:
      - args:
        - all
        env:
        - name: JAEGER_ENDPOINT
          value: http://otel-collector.platform.svc.cluster.local:14268/api/traces
        image: jaegertracing/example-hotrod:latest
        imagePullPolicy: IfNotPresent
        name: hotrod
        ports:
        - containerPort: 8080
      restartPolicy: Always
