name: build-pipeline

on:
  pull_request:
    branches:
      - develop
      - main
      - release/v*

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install tools
        run: make install-ci

      - name: Run unit tests
        run: make test-ci

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: cd frontend && yarn install
      - name: Run ESLint
        run: cd frontend && npm run lint
      - name: Run Jest
        run: cd frontend && npm run jest
      - name: TSC
        run: yarn tsc
        working-directory: ./frontend
      - name: Build frontend docker image
        shell: bash
        run: |
          make build-frontend-amd64

  build-query-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build  query-service image
        shell: bash
        run: |
          make build-query-service-amd64
